Update the clap version to avoid build errors.
With the old version of clap, I get errors like the following, which seems to
indicate that clap has changed how it satisfies these bounds between version 3
and version 4. This seems to depend on the fact that the library itself uses
version 4.

error[E0277]: the trait bound `StandardCmd: clap::Subcommand` is not satisfied
  --> crates/ociplex/src/main.rs:11:10
   |
11 | #[derive(Parser, Debug)]
   |          ^^^^^^ the trait `clap::Subcommand` is not implemented for `StandardCmd`
   |
   = help: the following other types implement trait `clap::Subcommand`:
             Box<T>
             Subcommand
   = note: this error originates in the derive macro `Parser` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `liboci_cli::Exec: FromArgMatches` is not satisfied
  --> crates/ociplex/src/main.rs:11:10
   |
11 | #[derive(Parser, Debug)]
   |          ^^^^^^ the trait `FromArgMatches` is not implemented for `liboci_cli::Exec`
   |
   = help: the following other types implement trait `FromArgMatches`:
             Box<T>
             Opts
             Subcommand
   = note: this error originates in the derive macro `Parser` (in Nightly builds, run with -Z macro-backtrace for more info)

Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>